---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Verify Jenkins installation
      command: systemctl status jenkins
      register: jenkins_status
      changed_when: false

    - name: Print Jenkins status
      debug:
        msg: "{{ jenkins_status.stdout }}"
